export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const  RESOLVE_GET_PRODUCT_LIST = 'RESOLVE_GET_PRODUCT_LIST';
export const GET_MATERIAL_LIST_INFO = "GET_MATERIAL_LIST_INFO";


export const GET_SEARCH_FILTER_COND = "GET_SEARCH_FILTER_COND";
export const RESOLVE_GET_SEARCH_FILTER_COND = "RESOLVE_GET_SEARCH_FILTER_COND";